postprocess:
  data_layout: NCHW
  detection_thr: 0.3
preprocess:
  crop:
  - 640
  - 640
  data_layout: NCHW
  mean:
  - 0
  - 0
  - 0
  resize:
  - 640
  - 640
  scale:
  - 0.003921568627
  - 0.003921568627
  - 0.003921568627
session:
  artifacts_folder: ''
  model_folder: model
  model_path: yolov5s_dfg_no_normalize.onnx
  session_name: onnxrt
target_device: pc
task_type: detection
